---
name: build-linux

on:
  pull_request:
  push:

jobs:
  build-linux:
    name: build-linux
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: dependencies
        run: |
          sudo apt update
          sudo apt install autotools-dev autoconf automake libtool libssl-dev libnss3-dev libmbedtls-dev libgnutls28-dev
      - name: gen
        run: |
          autoreconf -ivf
      - name: build
        run: |
          ./configure --enable-strict --enable-pedantic
          make distcheck
